# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import prime_api_pb2 as prime__api__pb2


class PrimeServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get_primes = channel.unary_unary(
        '/PrimeService/get_primes',
        request_serializer=prime__api__pb2.Request.SerializeToString,
        response_deserializer=prime__api__pb2.Response.FromString,
        )


class PrimeServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def get_primes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PrimeServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get_primes': grpc.unary_unary_rpc_method_handler(
          servicer.get_primes,
          request_deserializer=prime__api__pb2.Request.FromString,
          response_serializer=prime__api__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PrimeService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
